

# Class information for AMT_RedirectionService
# Generated by 'wbem' for use with ruby-wbem

require 'rubygems'
require 'cim'
require 'wbem'

module Wbem

  class AMT_RedirectionService < Wbem::Instance


    TYPEMAP = {

        # AMT_RedirectionService.ListenerEnabled
        "ListenerEnabled" => :boolean,

        # AMT_RedirectionService.AccessLog
        "AccessLog" => :string,

        # AMT_RedirectionService.EnabledState
        "EnabledState" => :uint16,

        # AMT_RedirectionService.RequestStateChange()
        "RequestStateChange" => [ :uint32, 
            [ "RequestedState", :uint16, :in ], 
            [ "Job", :class, :out ], 
            [ "TimeoutPeriod", :dateTime, :in ], 
          ],
        
        # AMT_RedirectionService.TerminateSession()
        "TerminateSession" => [ :uint32, 
            [ "SessionType", :uint32, :in ], 
          ],
        
        # CIM_Service.SystemCreationClassName
        "SystemCreationClassName" => :string,

        # CIM_Service.SystemName
        "SystemName" => :string,

        # CIM_Service.CreationClassName
        "CreationClassName" => :string,

        # CIM_Service.Name
        "Name" => :string,

        # CIM_Service.PrimaryOwnerName
        "PrimaryOwnerName" => :string,

        # CIM_Service.PrimaryOwnerContact
        "PrimaryOwnerContact" => :string,

        # CIM_Service.StartMode
        "StartMode" => :string,

        # CIM_Service.Started
        "Started" => :boolean,

        # CIM_Service.LoSID
        "LoSID" => :string,

        # CIM_Service.LoSOrgID
        "LoSOrgID" => :string,

        # CIM_Service.StartService()
        "StartService" => [ :uint32, 
          ],
        
        # CIM_Service.StopService()
        "StopService" => [ :uint32, 
          ],
        
        # CIM_Service.ChangeAffectedElementsAssignedSequence()
        "ChangeAffectedElementsAssignedSequence" => [ :uint32, 
            [ "ManagedElements", :class, :in ], 
            [ "AssignedSequence", :uint16, :in ], 
            [ "Job", :class, :out ], 
          ],
        
        # CIM_EnabledLogicalElement.OtherEnabledState
        "OtherEnabledState" => :string,

        # CIM_EnabledLogicalElement.RequestedState
        "RequestedState" => :uint16,

        # CIM_EnabledLogicalElement.EnabledDefault
        "EnabledDefault" => :uint16,

        # CIM_EnabledLogicalElement.TimeOfLastStateChange
        "TimeOfLastStateChange" => :dateTime,

        # CIM_EnabledLogicalElement.AvailableRequestedStates
        "AvailableRequestedStates" => :uint16,

        # CIM_EnabledLogicalElement.TransitioningToState
        "TransitioningToState" => :uint16,

        # CIM_ManagedSystemElement.InstallDate
        "InstallDate" => :dateTime,

        # CIM_ManagedSystemElement.OperationalStatus
        "OperationalStatus" => :uint16,

        # CIM_ManagedSystemElement.StatusDescriptions
        "StatusDescriptions" => :string,

        # CIM_ManagedSystemElement.Status
        "Status" => :string,

        # CIM_ManagedSystemElement.HealthState
        "HealthState" => :uint16,

        # CIM_ManagedSystemElement.CommunicationStatus
        "CommunicationStatus" => :uint16,

        # CIM_ManagedSystemElement.DetailedStatus
        "DetailedStatus" => :uint16,

        # CIM_ManagedSystemElement.OperatingStatus
        "OperatingStatus" => :uint16,

        # CIM_ManagedSystemElement.PrimaryStatus
        "PrimaryStatus" => :uint16,

        # CIM_ManagedElement.InstanceID
        "InstanceID" => :string,

        # CIM_ManagedElement.Caption
        "Caption" => :string,

        # CIM_ManagedElement.Description
        "Description" => :string,

        # CIM_ManagedElement.ElementName
        "ElementName" => :string,

        # CIM_ManagedElement.Generation
        "Generation" => :uint64,

    }
    
    def _typemap
      TYPEMAP
    end

  end # class
end # module
