

# Class information for AMT_RedirectionService
# Generated by 'wbem' for use with ruby-wbem

require 'rubygems'
require 'cim'
require 'wbem'

module Wbem

  class AMT_RedirectionService < Wbem::Instance


    TYPEMAP = {

        # AMT_RedirectionService.ListenerEnabled
        "ListenerEnabled" => :boolean,

        # AMT_RedirectionService.AccessLog
        "AccessLog" => :string,

        # AMT_RedirectionService.EnabledState
        "EnabledState" => :uint16,

        # AMT_RedirectionService.RequestStateChange()
        "RequestStateChange" => [ :uint32, 
            [ "RequestedState", :uint16, :in ], 
            [ "Job", :class, :out ], 
            [ "TimeoutPeriod", :dateTime, :in ], 
          ],
        
        # AMT_RedirectionService.TerminateSession()
        "TerminateSession" => [ :uint32, 
            [ "SessionType", :uint32, :in ], 
          ],
        
        # CIM_Service.SystemCreationClassName
        "SystemCreationClassName" => :string,

        # CIM_Service.SystemName
        "SystemName" => :string,

        # CIM_Service.CreationClassName
        "CreationClassName" => :string,

        # CIM_Service.Name
        "Name" => :string,

        # CIM_Service.PrimaryOwnerName
        "PrimaryOwnerName" => :string,

        # CIM_Service.PrimaryOwnerContact
        "PrimaryOwnerContact" => :string,

        # CIM_Service.StartMode
        "StartMode" => :string,

        # CIM_Service.Started
        "Started" => :boolean,

        # CIM_Service.LoSID
        "LoSID" => :string,

        # CIM_Service.LoSOrgID
        "LoSOrgID" => :string,

        # CIM_Service.StartService()
        "StartService" => [ :uint32, 
          ],
        
        # CIM_Service.StopService()
        "StopService" => [ :uint32, 
          ],
        
        # CIM_Service.ChangeAffectedElementsAssignedSequence()
        "ChangeAffectedElementsAssignedSequence" => [ :uint32, 
            [ "ManagedElements", :class, :in ], 
            [ "AssignedSequence", :uint16, :in ], 
            [ "Job", :class, :out ], 
          ],
        
        # CIM_EnabledLogicalElement.OtherEnabledState
        "OtherEnabledState" => :string,

        # CIM_EnabledLogicalElement.RequestedState
        "RequestedState" => :uint16,

        # CIM_EnabledLogicalElement.EnabledDefault
        "EnabledDefault" => :uint16,

        # CIM_EnabledLogicalElement.TimeOfLastStateChange
        "TimeOfLastStateChange" => :dateTime,

        # CIM_EnabledLogicalElement.AvailableRequestedStates
        "AvailableRequestedStates" => :uint16,

        # CIM_EnabledLogicalElement.TransitioningToState
        "TransitioningToState" => :uint16,

        # CIM_ManagedSystemElement.InstallDate
        "InstallDate" => :dateTime,

        # CIM_ManagedSystemElement.OperationalStatus
        "OperationalStatus" => :uint16,

        # CIM_ManagedSystemElement.StatusDescriptions
        "StatusDescriptions" => :string,

        # CIM_ManagedSystemElement.Status
        "Status" => :string,

        # CIM_ManagedSystemElement.HealthState
        "HealthState" => :uint16,

        # CIM_ManagedSystemElement.CommunicationStatus
        "CommunicationStatus" => :uint16,

        # CIM_ManagedSystemElement.DetailedStatus
        "DetailedStatus" => :uint16,

        # CIM_ManagedSystemElement.OperatingStatus
        "OperatingStatus" => :uint16,

        # CIM_ManagedSystemElement.PrimaryStatus
        "PrimaryStatus" => :uint16,

        # CIM_ManagedElement.InstanceID
        "InstanceID" => :string,

        # CIM_ManagedElement.Caption
        "Caption" => :string,

        # CIM_ManagedElement.Description
        "Description" => :string,

        # CIM_ManagedElement.ElementName
        "ElementName" => :string,

        # CIM_ManagedElement.Generation
        "Generation" => :uint64,

    }
    
    def _typemap
      TYPEMAP
    end

    #
    # Class constructor
    #   client - client instance, used for method invocation
    #            either a Wbem::CimxmlClient
    #            or a Wbem::WsmanClient
    #
    #   instance_ref - instance reference
    #                  either ObjectPath (Wbem::CimxmlClient) or
    #                  EndPointReference (Wbem::WsmanClient)
    #
    #   instance_data - instance data
    #                   Wbem::WsmanClient: Openwsman::XmlNode
    #                   Wbem::CimxmlClient: nil (instance_ref has all information)
    #
    def initialize client, instance_ref, instance_data = nil
      super
    end
    #
    # method_missing
    #   needs to be here to access TYPEMAP
    #
    def method_missing name, *args
      # http://stackoverflow.com/questions/8960685/ruby-why-does-puts-call-to-ary
      raise NoMethodError if name == :to_ary
      name = name.to_s
      assign = false
      if name[-1,1] == '=' # assignment
        name = name[0...-1]
        assign = true
      end
      type = TYPEMAP[name]
      if type.is_a? Array
        invoke(name, type, args)
      else
        return nil unless type # unknown property
        if assign
          # property assignment
          self[name] = Wbem::Conversion.from_ruby type, args[0]
        else
          # property read
          value = self[name]
          Wbem::Conversion.to_ruby type, value
        end
      end
    end # method_missing
  end # class
end # module
