

# Class information for CIM_KVMRedirectionSAP
# Generated by 'wbem' for use with ruby-wbem

require 'rubygems'
require 'cim'
require 'wbem'

module Wbem

  class CIM_KVMRedirectionSAP < Wbem::Instance


    TYPEMAP = {

        # CIM_KVMRedirectionSAP.KVMProtocol
        "KVMProtocol" => :uint16,

        # CIM_KVMRedirectionSAP.OtherKVMProtocol
        "OtherKVMProtocol" => :string,

        # CIM_ServiceAccessPoint.SystemCreationClassName
        "SystemCreationClassName" => :string,

        # CIM_ServiceAccessPoint.SystemName
        "SystemName" => :string,

        # CIM_ServiceAccessPoint.CreationClassName
        "CreationClassName" => :string,

        # CIM_ServiceAccessPoint.Name
        "Name" => :string,

        # CIM_EnabledLogicalElement.EnabledState
        "EnabledState" => :uint16,

        # CIM_EnabledLogicalElement.OtherEnabledState
        "OtherEnabledState" => :string,

        # CIM_EnabledLogicalElement.RequestedState
        "RequestedState" => :uint16,

        # CIM_EnabledLogicalElement.EnabledDefault
        "EnabledDefault" => :uint16,

        # CIM_EnabledLogicalElement.TimeOfLastStateChange
        "TimeOfLastStateChange" => :dateTime,

        # CIM_EnabledLogicalElement.AvailableRequestedStates
        "AvailableRequestedStates" => :uint16,

        # CIM_EnabledLogicalElement.TransitioningToState
        "TransitioningToState" => :uint16,

        # CIM_EnabledLogicalElement.RequestStateChange()
        "RequestStateChange" => [ :uint32, 
            [ "RequestedState", :uint16, :in ], 
            [ "Job", :class, :out ], 
            [ "TimeoutPeriod", :dateTime, :in ], 
          ],
        
        # CIM_ManagedSystemElement.InstallDate
        "InstallDate" => :dateTime,

        # CIM_ManagedSystemElement.OperationalStatus
        "OperationalStatus" => :uint16,

        # CIM_ManagedSystemElement.StatusDescriptions
        "StatusDescriptions" => :string,

        # CIM_ManagedSystemElement.Status
        "Status" => :string,

        # CIM_ManagedSystemElement.HealthState
        "HealthState" => :uint16,

        # CIM_ManagedSystemElement.CommunicationStatus
        "CommunicationStatus" => :uint16,

        # CIM_ManagedSystemElement.DetailedStatus
        "DetailedStatus" => :uint16,

        # CIM_ManagedSystemElement.OperatingStatus
        "OperatingStatus" => :uint16,

        # CIM_ManagedSystemElement.PrimaryStatus
        "PrimaryStatus" => :uint16,

        # CIM_ManagedElement.InstanceID
        "InstanceID" => :string,

        # CIM_ManagedElement.Caption
        "Caption" => :string,

        # CIM_ManagedElement.Description
        "Description" => :string,

        # CIM_ManagedElement.ElementName
        "ElementName" => :string,

        # CIM_ManagedElement.Generation
        "Generation" => :uint64,

    }
    
    def _typemap
      TYPEMAP
    end

  end # class
end # module
