

# Class information for IPS_KVMRedirectionSettingData
# Generated by 'wbem' for use with ruby-wbem

require 'rubygems'
require 'cim'
require 'wbem'

module Wbem

  class IPS_KVMRedirectionSettingData < Wbem::Instance


    TYPEMAP = {

        # IPS_KVMRedirectionSettingData.EnabledByMEBx
        "EnabledByMEBx" => :boolean,

        # IPS_KVMRedirectionSettingData.Is5900PortEnabled
        "Is5900PortEnabled" => :boolean,

        # IPS_KVMRedirectionSettingData.OptInPolicy
        "OptInPolicy" => :boolean,

        # IPS_KVMRedirectionSettingData.OptInPolicyTimeout
        "OptInPolicyTimeout" => :uint16,

        # IPS_KVMRedirectionSettingData.SessionTimeout
        "SessionTimeout" => :uint16,

        # IPS_KVMRedirectionSettingData.RFBPassword
        "RFBPassword" => :string,

        # IPS_KVMRedirectionSettingData.DefaultScreen
        "DefaultScreen" => :uint8,

        # IPS_KVMRedirectionSettingData.TerminateSession()
        "TerminateSession" => [ :uint32, 
          ],
        
        # CIM_SettingData.InstanceID
        "InstanceID" => :string,

        # CIM_SettingData.ElementName
        "ElementName" => :string,

        # CIM_SettingData.ConfigurationName
        "ConfigurationName" => :string,

        # CIM_SettingData.ChangeableType
        "ChangeableType" => :uint16,

        # CIM_SettingData.ComponentSetting
        "ComponentSetting" => :string,

        # CIM_SettingData.SoID
        "SoID" => :string,

        # CIM_SettingData.SoOrgID
        "SoOrgID" => :string,

        # CIM_ManagedElement.Caption
        "Caption" => :string,

        # CIM_ManagedElement.Description
        "Description" => :string,

        # CIM_ManagedElement.Generation
        "Generation" => :uint64,

    }
    
    def _typemap
      TYPEMAP
    end

  end # class
end # module
